export const LightColors = {
  primary: '#1E1E1E',        
  onPrimary: '#FFFFFF',
  primaryContainer: '#E0E0E0', 
  onPrimaryContainer: '#1E1E1E',
  secondary: '#FF6D00',    
  onSecondary: '#FFFFFF',
  secondaryContainer: '#FFE0B2',
  onSecondaryContainer: '#4A2500',
  tertiary: '#FFAB40', 
  onTertiary: '#1E1E1E',
  tertiaryContainer: '#FFE8D2',
  onTertiaryContainer: '#4A2C00',
  error: '#D32F2F',
  onError: '#FFFFFF',
  errorContainer: '#F9C0C0',
  onErrorContainer: '#5A0000',
  background: '#F5F5F5',
  onBackground: '#1E1E1E',
  outline: '#B0B0B0',
  shadow: '#CCCCCC',
  surface: '#FFFFFF',
  onSurface: '#1E1E1E',
  surfaceVariant: '#F2F2F2',
  onSurfaceVariant: '#3A3A3A',
};

export const DarkColors = {
  primary: '#F2F2F2',      
  onPrimary: '#1E1E1E',
  primaryContainer: '#2A2A2A',
  onPrimaryContainer: '#FFFFFF',
  secondary: '#FF8F00',
  onSecondary: '#1E1E1E',
  secondaryContainer: '#FF6D00',
  onSecondaryContainer: '#FFFFFF',
  tertiary: '#FFB74D',
  onTertiary: '#1E1E1E',
  tertiaryContainer: '#FF8F00',
  onTertiaryContainer: '#FFFFFF',
  error: '#EF9A9A',
  onError: '#5A0000',
  errorContainer: '#D32F2F',
  onErrorContainer: '#FFFFFF',
  background: '#121212',
  onBackground: '#FFFFFF',
  outline: '#666666',
  shadow: '#000000',
  surface: '#1E1E1E',
  onSurface: '#FFFFFF',
  surfaceVariant: '#2C2C2C',
  onSurfaceVariant: '#DDDDDD',
};
